default_context:
  project_name: 'library'
  project_slug: 'library'
  domain_main: 'library.com'
  domain_staging: 'stag.library.com'
  docker_swarm_stack_name_main: 'library-com'
  docker_swarm_stack_name_staging: 'stag-library-com'
  secret_key: 'library'
  first_superuser: 'admin@library.com'
  first_superuser_password: 'library'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.library.com", "https://stag.library.com", "https://library.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@library.com'
  postgres_password: 'library'
  pgadmin_default_user: 'admin@library.com'
  pgadmin_default_user_password: 'library'
  traefik_constraint_tag: 'library.com'
  traefik_constraint_tag_staging: 'stag.library.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:library'
  sentry_dsn: ''
  docker_image_prefix: 'library'
  docker_image_backend: 'librarybackend'
  docker_image_celeryworker: 'libraryceleryworker'
  docker_image_frontend: 'libraryfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
